version: "3.8"

services:
  app:
    container_name: perkastor-dev
    image: perkastor-dev
    build:
      target: development
      context: ./
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: development
      PORT: 3000
      COVERAGE:
      LOG_LEVEL:
    volumes:
      - .:/usr/src/app # Sync host and container
      - nodemodules:/src/node_modules # Cache node_modules
    ports:
      - 3000:3000

volumes:
    nodemodules: {}