version: "3.8"

services:
  app:
    container_name: perkastor-prod
    image: perkastor-prod
    build:
      context: .
      target: "runner"
      dockerfile: Dockerfile.next13
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
